# Generated by Django 2.0.7 on 2019-01-02 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcq', '0002_auto_20180727_2247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='content',
            field=models.CharField(help_text='Enter the answer text that \\ you want displayed', max_length=1000, verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='mcqquestion',
            name='answer_order',
            field=models.CharField(blank=True, choices=[('content', 'Content'), ('none', 'None')], help_text='The order in which multichoice \\ answer options are displayed \\ to the user', max_length=30, null=True, verbose_name='Answer Order'),
        ),
    ]
