# Generated by Django 2.1.5 on 2019-01-21 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='user',
            new_name='feedbackUser',
        ),
    ]
