# Generated by Django 2.0.7 on 2019-01-16 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='userCreated',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
