# Generated by Django 2.0.7 on 2019-01-17 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_auto_20190116_2054'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='checked_agreeGdprBox',
            field=models.BooleanField(default=True),
        ),
    ]
