# Generated by Django 2.0.7 on 2019-01-07 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(blank=True, max_length=40, null=True)),
                ('question', models.TextField(blank=True, null=True)),
                ('correct', models.TextField(blank=True, null=True)),
                ('wrong1', models.TextField(blank=True, null=True)),
                ('wrong2', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
