# Generated by Django 2.0.7 on 2019-01-08 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Exam1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testtext',
            name='jeLegislativa',
            field=models.BooleanField(default=True),
        ),
    ]
