# Generated by Django 2.1.5 on 2019-01-21 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Exam1', '0002_testtext_jelegislativa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testtext',
            name='jeLegislativa',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
